Setting up a placeholder api with deployment
openearthplatforminitiative/client-registration-api pull request #1
Opened 2024-10-11 06:57 UTC by kstigen

2024-11-14 09:56 UTC, daniejoh requested changes

2024-11-14 09:56 UTC, daniejoh commented on keycloak/keycloak.go
> +			clientList = append(clientList, &models.Client{InternalID: cl.ID, ClientID: cl.ClientID, ClientName: cl.Name, ClientSecret: cl.Secret})
Could you have used lo.Filter here?
```
even := lo.Filter(clients, func(client models.Client, index int) bool {
    return s.HasPrefix(*client.ClientID, UserName)
})
```
I think it makes it more readable.

2024-11-14 09:56 UTC, daniejoh commented on deployment/argocd/app.yaml
> +    targetRevision: Issue-253-Simplest-possible-API
Change this to HEAD.

2024-11-14 09:56 UTC, daniejoh commented on README.md
> +```
Nitpicky, but you have pushed .mockery.yaml, can you refer to that file instead?

2024-11-14 09:56 UTC, daniejoh commented on README.md
> +brew install mockery
Not everyone might use brew. Refer to installation docs instead? https://vektra.github.io/mockery/latest/installation/#installation

2024-11-14 09:56 UTC, daniejoh commented on deployment/kubernetes/client-registration-api.yaml
> +#        prometheus.io/path: "/metrics"
Are we dropping logs and metrics for now?

2024-11-14 09:56 UTC, daniejoh commented on keycloak/keycloak.go
> +		if s.HasPrefix(*cl.ClientID, UserName) {
I think you should avoid import aliasing here, and just use `strings.HasPrefix` instead of `s.HasPrefix`.

2024-11-14 09:56 UTC, daniejoh commented on keycloak/keycloak.go
> +		if s.HasPrefix(*cl.ClientID, UserName) {
Although we are not following this style guide, I agree with the statement that "In all other scenarios, import aliases should be avoided unless there is a direct conflict between imports." https://github.com/uber-go/guide/blob/master/style.md#import-aliasing 

What do you think?

2024-11-14 09:56 UTC, daniejoh commented on tests/unit/data/test_data.go
> +	ut "github.com/go-playground/universal-translator"
Same as with strings earlier. I believe this should not be aliased.

2024-11-14 14:39 UTC, kstigen commented on keycloak/keycloak.go
> +			clientList = append(clientList, &models.Client{InternalID: cl.ID, ClientID: cl.ClientID, ClientName: cl.Name, ClientSecret: cl.Secret})
Already done, but forgotten to push :)

2024-11-14 14:42 UTC, kstigen commented on deployment/kubernetes/client-registration-api.yaml
> +#        prometheus.io/path: "/metrics"
Yes, but not really. Decided to do this in a separate PR. Have to find out how to do prometheus metrics with gin.

2024-11-14 14:44 UTC, kstigen commented on keycloak/keycloak.go
> +		if s.HasPrefix(*cl.ClientID, UserName) {
I'm fine with avoiding import aliasing, where we can.

2024-11-14 14:45 UTC, kstigen commented on tests/unit/data/test_data.go
> +	ut "github.com/go-playground/universal-translator"
This needs to be aliased, as the package name is `ut` which does not match the last element of the import path.

2024-11-15 08:26 UTC, daniejoh commented on deployment/kubernetes/client-registration-api.yaml
> +#        prometheus.io/path: "/metrics"
Okay, I have done the same for now on the agriculture api.

2024-11-15 08:27 UTC, daniejoh approved these changes

2024-11-15 10:13 UTC, merged